import { Roboto_Flex } from 'next/font/google';
import { Navbar } from './components/Navbar';

import Data from './data/navbar.json';

import './globals.css';

const font = Roboto_Flex({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const { image, title, menuNav } = Data;

  return (
    <html lang="es">
      <body className={font.className}>
        <Navbar image={image} title={title} menuNav={menuNav} />
        {children}
      </body>
    </html>
  );
}
